package com.unifest.android.feature.stamp.preview

import androidx.compose.ui.tooling.preview.PreviewParameterProvider
import com.unifest.android.core.model.StampBoothModel
import com.unifest.android.feature.stamp.viewmodel.StampUiState
import kotlinx.collections.immutable.persistentListOf

internal class StampPreviewParameterProvider : PreviewParameterProvider<StampUiState> {
    override val values = sequenceOf(
        StampUiState(
            stampBoothList = persistentListOf(
                StampBoothModel(
                    id = 0,
                    category = "부스 카테고리",
                    enabled = true,
                    latitude = 0F,
                    longitude = 0F,
                    location = "부스 위치",
                    name = "부스 이름",
                    waitingEnabled = true,
                    stampEnabled = true,
                ),
                StampBoothModel(
                    id = 1,
                    category = "부스 카테고리",
                    enabled = true,
                    latitude = 0F,
                    longitude = 0F,
                    location = "부스 위치",
                    name = "부스 이름",
                    waitingEnabled = true,
                    stampEnabled = true,
                ),
                StampBoothModel(
                    id = 2,
                    category = "부스 카테고리",
                    enabled = true,
                    latitude = 0F,
                    longitude = 0F,
                    location = "부스 위치",
                    name = "부스 이름",
                    waitingEnabled = true,
                    stampEnabled = true,
                ),
                StampBoothModel(
                    id = 3,
                    category = "부스 카테고리",
                    enabled = true,
                    latitude = 0F,
                    longitude = 0F,
                    location = "부스 위치",
                    name = "부스 이름",
                    waitingEnabled = true,
                    stampEnabled = true,
                ),
                StampBoothModel(
                    id = 4,
                    category = "부스 카테고리",
                    enabled = true,
                    latitude = 0F,
                    longitude = 0F,
                    location = "부스 위치",
                    name = "부스 이름",
                    waitingEnabled = true,
                    stampEnabled = true,
                ),
                StampBoothModel(
                    id = 5,
                    category = "부스 카테고리",
                    enabled = true,
                    latitude = 0F,
                    longitude = 0F,
                    location = "부스 위치",
                    name = "부스 이름",
                    waitingEnabled = true,
                    stampEnabled = true,
                ),
                StampBoothModel(
                    id = 6,
                    category = "부스 카테고리",
                    enabled = true,
                    latitude = 0F,
                    longitude = 0F,
                    location = "부스 위치",
                    name = "부스 이름",
                    waitingEnabled = true,
                    stampEnabled = true,
                ),
                StampBoothModel(
                    id = 7,
                    category = "부스 카테고리",
                    enabled = true,
                    latitude = 0F,
                    longitude = 0F,
                    location = "부스 위치",
                    name = "부스 이름",
                    waitingEnabled = true,
                    stampEnabled = true,
                ),
                StampBoothModel(
                    id = 8,
                    category = "부스 카테고리",
                    enabled = true,
                    latitude = 0F,
                    longitude = 0F,
                    location = "부스 위치",
                    name = "부스 이름",
                    waitingEnabled = true,
                    stampEnabled = true,
                ),
                StampBoothModel(
                    id = 9,
                    category = "부스 카테고리",
                    enabled = true,
                    latitude = 0F,
                    longitude = 0F,
                    location = "부스 위치",
                    name = "부스 이름",
                    waitingEnabled = true,
                    stampEnabled = true,
                ),
                StampBoothModel(
                    id = 10,
                    category = "부스 카테고리",
                    enabled = true,
                    latitude = 0F,
                    longitude = 0F,
                    location = "부스 위치",
                    name = "부스 이름",
                    waitingEnabled = true,
                    stampEnabled = true,
                ),
                StampBoothModel(
                    id = 11,
                    category = "부스 카테고리",
                    enabled = true,
                    latitude = 0F,
                    longitude = 0F,
                    location = "부스 위치",
                    name = "부스 이름",
                    waitingEnabled = true,
                    stampEnabled = true,
                ),
            ),
        ),
    )
}
