name: Android CI

env:
    GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false"
    GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

on:
    pull_request:

concurrency:
    group: build-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci-build:
        runs-on: ubuntu-latest

        if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'corretto'
                    java-version: 17

            -   name: Setup Android SDK
                uses: android-actions/setup-android@v2

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
                with:
                    gradle-home-cache-cleanup: true

            -   name: Generate secrets.properties
                run: |
                    echo '${{ secrets.SECRETS_PROPERTIES }}' >> ./secrets.properties

            -   name: Generate local.properties
                run: |
                    echo '${{ secrets.LOCAL_PROPERTIES }}' >> ./local.properties

            -   name: Generate keystore.properties
                run: |
                    echo '${{ secrets.KEYSTORE_PROPERTIES }}' >> ./keystore.properties

            -   name: Generate google-services.json
                run: echo '${{ secrets.GOOGLE_SERVICES }}' | base64 --d > ./app/google-services.json

            -   name: Code style checks
                run: ./gradlew ktlintCheck detekt

            -   name: Run build
                run: ./gradlew buildDebug --stacktrace
